name: CI

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Fix git checkout line endings
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2.3.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install
        run: npm install --engine-strict
      - name: Lint
        run: npm run lint
      - name: Testsuite
        run: npm run coverage
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v2.0.2
        with:
          file: ./coverage/lcov.info
          env_vars: CI_OS,NODE_VERSION
        env:
          CI_OS: ${{ matrix.os }}
          NODE_VERSION: ${{ matrix.node-version }}
  automerge:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
