name: Publish documentation

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Fetch all git branches
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 14.x
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Restore npm cache
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3.0.11
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
      - run: npm install --engine-strict
      - run: npm run docs
      - uses: malept/github-action-gh-pages@v1.3.0
        with:
          defaultBranch: main
          docsPath: docs
          gitCommitMessage: "Publish [skip ci]"
          showUnderscoreFiles: true
          versionDocs: true
        env:
          GH_PAGES_SSH_DEPLOY_KEY: ${{ secrets.DOCS_SSH_DEPLOY_KEY }}
